### ISSUE TITLE
Hello, I am learning about flight delays. I'd like to ask you some questions

### ISSUE THREAD

**Issue by ZZgodDog** [nive927/Flight_Delay_Prediction#1]
I learned 05_Classification, but there is nothing similar in your project`model = joblib.load("../Data/feature_importance_model.joblib")`。I'm a beginner. I wanted to ask you. Can this model be made public? Looking forward to your recovery.

**Comment by nive927** [comment]
Hello!

I'm glad you enjoyed reading through the work.

Unfortunately, I am unable to make the data and models public.

Thank you.
